#!/bin/bash

# for my private IPs

dataArray=(
    'k8sm01 10.10.11.81 k8s-master'
    'k8sw01 10.10.11.82 k8s-worker1'
    'k8sw02 10.10.11.83 k8s-worker2'
)

IF_ETH0=`/sbin/ip -f inet -o addr show eth0 | awk '( $9 == "eth0\\\" ) {print $4}' | cut -d/ -f 1`
echo $IF_ETH0

for i in "${dataArray[@]}";
do
  data=(${i[@]})
  hostname=${data[0]}
  ip=${data[1]}
  role=${data[2]}
#  echo $hostname $ip $role

  if [ "$ip" = "$IF_ETH0" ]; then
    sudo sh -c "echo '127.0.1.1    $hostname' >> /etc/hosts"
    sudo sh -c "echo $hostname > /etc/hostname"
  else
    echo "ip address no match"
    sudo sh -c "echo '$ip    $hostname' >> /etc/hosts"
  fi

done

#sudo sed --in-place '$ s/$/ cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory/g' /boot/cmdline.txt
sudo reboot
