#!/bin/bash

####################################################################################################
# F5 Container Ingress Services Add BIG-IP device to flannel VXLAN
####################################################################################################

##########################################################################################
## Get Docker Engine - Community for Debian
## reference url:
## https://clouddocs.f5.com/containers/v2/kubernetes/kctlr-use-bigip-k8s.html#use-bigip-k8s-flannel
##########################################################################################

##################################################
### Set up the BIG-IP system
##################################################

tmsh create net tunnels vxlan fl-vxlan port 8472 flooding-type none
tmsh create net tunnels tunnel flannel_vxlan key 1 profile fl-vxlan local-address 10.10.11.80

