#!/bin/bash

### for Debian k8s master setup  
### reference url:
### https://docs.docker.com/install/linux/docker-ce/debian/

#############################################
###         SET UP THE REPOSITORY         ###
#############################################

# 1. Update the apt package index:
sudo apt-get update

# 2. Install packages to allow apt to use a repository over HTTPS:
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common
    
# 3. Add Docker’s official GPG key:
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

# 4. Use the following command to set up the stable repository. 
#    To add the nightly or test repository, add the word nightly or test (or both) 
#    after the word stable in the commands below. Learn about nightly and test channels.
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

#############################################
###   INSTALL DOCKER ENGINE - COMMUNITY   ###
#############################################

# 1. Update the apt package index.
sudo apt-get update

# 2. Install the latest version of Docker Engine - Community and containerd, 
#    or go to the next step to install a specific version:
sudo apt-get install docker-ce docker-ce-cli containerd.io

# TBE...


