#!/bin/bash

##########
####################################################################################################
# for Debian k8s master setup
####################################################################################################

##########################################################################################
## Get Docker Engine - Community for Debian
## reference url:
## https://docs.docker.com/install/linux/docker-ce/debian/
##########################################################################################

##################################################
### SET UP THE REPOSITORY
##################################################

# 1. Update the apt package index:
#sudo apt-get update
sudo apt-get update -y

# 2. Install packages to allow apt to use a repository over HTTPS:
#sudo apt-get install \
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common
    
# 3. Add Docker’s official GPG key:
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

# 4. Use the following command to set up the stable repository. 
#    To add the nightly or test repository, add the word nightly or test (or both) 
#    after the word stable in the commands below. Learn about nightly and test channels.
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

##################################################
### INSTALL DOCKER ENGINE - COMMUNITY
##################################################

# 1. Update the apt package index.
#sudo apt-get update
sudo apt-get update -y

# 2. Install the latest version of Docker Engine - Community and containerd, 
#    or go to the next step to install a specific version:
#sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo apt-get install -y docker-ce docker-ce-cli containerd.io


##########################################################################################
## k8s setup with kubeadm
## reference url:
## https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
##########################################################################################

##################################################
### Installing kubeadm, kubelet and kubectl
##################################################

#apt-get update && apt-get install -y apt-transport-https curl
sudo apt-get update -y && sudo apt-get install -y apt-transport-https curl

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# change command `cat` to `tee` for sudo
#cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
#deb https://apt.kubernetes.io/ kubernetes-xenial main
#EOF

sudo tee /etc/apt/sources.list.d/kubernetes.list <<EOF
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

#apt-get update
sudo apt-get update -y

#apt-get install -y kubelet kubeadm kubectl
sudo apt-get install -y kubelet kubeadm kubectl

#apt-mark hold kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

##################################################
### Configure cgroup driver used by kubelet 
### on control-plane node
##################################################

# When using Docker, kubeadm will automatically detect the cgroup driver for 
# the kubelet and set it in the /var/lib/kubelet/kubeadm-flags.env file during runtime.
# 
# If you are using a different CRI, you have to modify the 
# file /etc/default/kubelet with your cgroup-driver value, like so:

#KUBELET_EXTRA_ARGS=--cgroup-driver=<value>

# This file will be used by kubeadm init and kubeadm join to source extra 
# user defined arguments for the kubelet.
# 
# Please mind, that you only have to do that if the cgroup driver of your CRI 
# is not cgroupfs, because that is the default value in the kubelet already.
# 
# Restarting the kubelet is required:

#systemctl daemon-reload
#systemctl restart kubelet

# The automatic detection of cgroup driver for other container runtimes like CRI-O and containerd is work in progress

##################################################
### Creating a single control-plane cluster 
### with kubeadm 
##################################################

#kubeadm init <args>

# Case. Use calico
#kubeadm init --pod-network-cidr=192.168.0.0/16

# Case. Use flannel
#kubeadm init --pod-network-cidr=10.244.0.0/16

kubeadm init --pod-network-cidr=10.244.0.0/16

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config



# TBE...





