#!/bin/bash
DOCKER_VERSION=5:18.09.8~3-0~debian-stretch

####################################################################################################
# for Debian k8s worker setup
####################################################################################################

##########################################################################################
## Get Docker Engine - Community for Debian
## reference url:
## https://docs.docker.com/install/linux/docker-ce/debian/
##########################################################################################

##################################################
### SET UP THE REPOSITORY
##################################################

# 1. Update the apt package index:
cat << EOF
##command##
## sudo apt-get update -y
EOF

#sudo apt-get update
sudo apt-get update -y

# 2. Install packages to allow apt to use a repository over HTTPS:
cat << EOF
##command##
## sudo apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common
## 
EOF

#sudo apt-get install \
sudo apt-get install -y \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common
    
# 3. Add Docker’s official GPG key:
cat << EOF
##command##
## curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
## 
EOF

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

# 4. Use the following command to set up the stable repository. 
#    To add the nightly or test repository, add the word nightly or test (or both) 
#    after the word stable in the commands below. Learn about nightly and test channels.
cat << EOF
##command##
## sudo add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/debian \
        $(lsb_release -cs) \
        stable"
## 
EOF

sudo add-apt-repository \
     "deb [arch=amd64] https://download.docker.com/linux/debian \
     $(lsb_release -cs) \
     stable"

##################################################
### INSTALL DOCKER ENGINE - COMMUNITY
##################################################

# 1. Update the apt package index.
cat << EOF
##command##
## sudo apt-get update -y
## 
EOF

#sudo apt-get update
sudo apt-get update -y

# 2. Install the latest version of Docker Engine - Community and containerd, 
#    or go to the next step to install a specific version:
#cat << EOF
##command##
## sudo apt-get install -y docker-ce docker-ce-cli containerd.io
## 
#EOF

#sudo apt-get install docker-ce docker-ce-cli containerd.io
#sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# 3. To install a specific version of Docker Engine - Community, 
# list the available versions in the repo, then select and install:

# List the versions available in your repo:
apt-cache madison docker-ce

echo "########## SPECIFIC DOCKER VERSION ###########"
echo "Specific Docker Version=$DOCKER_VERSION"
cat << EOF
##command##
## 
## sudo apt-get install -y docker-ce=$DOCKER_VERSION docker-ce-cli=$DOCKER_VERSION containerd.io
## 
EOF

sudo apt-get install -y docker-ce=$DOCKER_VERSION docker-ce-cli=$DOCKER_VERSION containerd.io

##########################################################################################
## k8s setup with kubeadm
## reference url:
## https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
##########################################################################################

##################################################
### Installing kubeadm, kubelet and kubectl
##################################################

cat << EOF
##command##
## sudo apt-get update -y && sudo apt-get install -y apt-transport-https curl
##
## curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
##
## sudo tee /etc/apt/sources.list.d/kubernetes.list <<E0F
## deb https://apt.kubernetes.io/ kubernetes-xenial main
## E0F
##
## sudo apt-get update -y
## sudo apt-get install -y kubelet kubeadm kubectl
## sudo apt-mark hold kubelet kubeadm kubectl
## 
EOF

#apt-get update && apt-get install -y apt-transport-https curl
sudo apt-get update -y && sudo apt-get install -y apt-transport-https curl

curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

# change command `cat` to `tee` for sudo
#cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
#deb https://apt.kubernetes.io/ kubernetes-xenial main
## 
#EOF

sudo tee /etc/apt/sources.list.d/kubernetes.list <<EOF
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF

#apt-get update
sudo apt-get update -y

#apt-get install -y kubelet kubeadm kubectl
sudo apt-get install -y kubelet kubeadm kubectl

#apt-mark hold kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl


##################################################
### Join kubernetes cluster 
##################################################

bash -c "$(curl -fsS http://10.10.11.81:9999)"

echo "finished!"
